//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TlkLocalisationTool.UI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TlkLocalisationTool.UI.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Context Selector - StrRef {0}.
        /// </summary>
        internal static string ContextSelector_Title {
            get {
                return ResourceManager.GetString("ContextSelector_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string DefaultTitle {
            get {
                return ResourceManager.GetString("DefaultTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [END DIALOGUE].
        /// </summary>
        internal static string DlgViewer_EndDialogueDisplayText {
            get {
                return ResourceManager.GetString("DlgViewer_EndDialogueDisplayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {LINK} .
        /// </summary>
        internal static string DlgViewer_LinkTag {
            get {
                return ResourceManager.GetString("DlgViewer_LinkTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [CONTINUE].
        /// </summary>
        internal static string DlgViewer_NoTextDisplayText {
            get {
                return ResourceManager.GetString("DlgViewer_NoTextDisplayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OWNER.
        /// </summary>
        internal static string DlgViewer_OwnerSpeaker {
            get {
                return ResourceManager.GetString("DlgViewer_OwnerSpeaker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLAYER.
        /// </summary>
        internal static string DlgViewer_PlayerSpeaker {
            get {
                return ResourceManager.GetString("DlgViewer_PlayerSpeaker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DLG Viewer - {0}.
        /// </summary>
        internal static string DlgViewer_Title {
            get {
                return ResourceManager.GetString("DlgViewer_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry Editor - StrRef {0}.
        /// </summary>
        internal static string EntryEditor_Title {
            get {
                return ResourceManager.GetString("EntryEditor_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ErrorMessage_Title {
            get {
                return ResourceManager.GetString("ErrorMessage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field {0} had unexpected type {1}..
        /// </summary>
        internal static string GffDataParser_FieldHadUnexpectedTypeMessage {
            get {
                return ResourceManager.GetString("GffDataParser_FieldHadUnexpectedTypeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GFF Viewer - {0}.
        /// </summary>
        internal static string GffViewer_Title {
            get {
                return ResourceManager.GetString("GffViewer_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string InformationMessage_Title {
            get {
                return ResourceManager.GetString("InformationMessage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encoding was invalid. Default encoding was selected instead..
        /// </summary>
        internal static string SettingsEditor_InvalidEncodingNameMessage {
            get {
                return ResourceManager.GetString("SettingsEditor_InvalidEncodingNameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected file is not a TLK file.
        /// </summary>
        internal static string SettingsEditor_SelectedFileIsNotTlkMessage {
            get {
                return ResourceManager.GetString("SettingsEditor_SelectedFileIsNotTlkMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SettingsEditor_Title {
            get {
                return ResourceManager.GetString("SettingsEditor_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row names.
        /// </summary>
        internal static string TdaViewer_RowNamesColumnName {
            get {
                return ResourceManager.GetString("TdaViewer_RowNamesColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2DA Viewer - {0}.
        /// </summary>
        internal static string TdaViewer_Title {
            get {
                return ResourceManager.GetString("TdaViewer_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lookup file is not yet generated. Do you want to generate it now?
        ///NOTE: it might take couple of minutes..
        /// </summary>
        internal static string TlkViewer_LookupFileIsNotGeneratedMessage {
            get {
                return ResourceManager.GetString("TlkViewer_LookupFileIsNotGeneratedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lookup file was generated. Now context is available for entries..
        /// </summary>
        internal static string TlkViewer_LookupFileWasGeneratedMessage {
            get {
                return ResourceManager.GetString("TlkViewer_LookupFileWasGeneratedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TLK Localisation Tool.
        /// </summary>
        internal static string TlkViewer_Title {
            get {
                return ResourceManager.GetString("TlkViewer_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to setup .tlk file paths..
        /// </summary>
        internal static string TlkViewer_TlkFilePathsAreNotSetUpMessage {
            get {
                return ResourceManager.GetString("TlkViewer_TlkFilePathsAreNotSetUpMessage", resourceCulture);
            }
        }
    }
}
